name: "Main workflow"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: CE2FS build 
        run: "python ./scripts/build.py --check"

      - name: Collect table version
        id: collect_version
        run: source BUILD_ENV && echo tag=v${TABLE_VERSION} >> $GITHUB_OUTPUT

      - name: Upload build
        id: upload_build
        uses: actions/upload-artifact@v4
        with:
          name: ER_TGA_${{ steps.collect_version.outputs.tag }}
          path: dist
          retention-days: 5

    outputs:
      release-tag: ${{ steps.collect_version.outputs.tag }}
      build-artifact-name: ER_TGA_${{ steps.collect_version.outputs.tag }}
  
  check-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          sparse-checkout: BUILD_ENV
      
      - name: Ensure version was updated
        run: |
          source BUILD_ENV
          if git show-ref --tags --verify --quiet "refs/tags/v${TABLE_VERSION}"; then
            echo "Release v${TABLE_VERSION} already exists"
            exit 1
          fi
  
  generate-changelog:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CHANGELOG.md
            BUILD_ENV
      
      - name: Extract changelog section
        id: extract_changelog
        run: |
          source BUILD_ENV
          escaped=$(echo "v${TABLE_VERSION}" | sed 's/\./\\./g')
          changelog=$(grep -zoP "## \[$escaped\](?:.|\n)*?\n## " CHANGELOG.md | sed '1d; $ d')
          if [ -z "${changelog}" ]; then
            echo "No changelog written for release v${TABLE_VERSION}. Aborting."
            exit 1
          fi
          {
            echo 'changelog<<EOF'
            echo "## Elden Ring app ver. ${GAME_VERSION}"
            echo "${changelog}"
            echo EOF
          } >> $GITHUB_OUTPUT
        
    outputs:
      changelog: ${{ steps.extract_changelog.outputs.changelog }}

  publish-release:
    runs-on: ubuntu-latest
    needs:
      - build
      - check-version
      - generate-changelog
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.build-artifact-name }}
          path: dist
      
      - name: Create zip
        run: zip ${{ needs.build.outputs.build-artifact-name }}.zip dist/* -r
      
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ needs.build.outputs.release-tag }}
          tag_name: ${{ needs.build.outputs.release-tag }}
          body: ${{ needs.generate-changelog.outputs.changelog }}
          files: ${{ needs.build.outputs.build-artifact-name }}.zip
